development:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :user_name: callmemc@gmail.com
  :password: 21326241
  :enable_starttls_auto: true
production:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :user_name: callmemc@gmail.com
  :password: 21326241
  :enable_starttls_auto: true